"""new fields in user model

Revision ID: 955bee34e2f6
Revises: 39b3ee59f9d4
Create Date: 2023-03-09 16:17:54.503612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955bee34e2f6'
down_revision = '39b3ee59f9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
